export const testData = [
{
    win: 2345,
    cardId: 1,
    cardComponent: 'INVENTORY',
    cardSubComponent: 'DC Inv',
    cardTask: 'DC Trapped Inv',
    cardLevel: 'Item-DC', 
    taskCount: 2417, 
    updateDate: '2019-01-14',
    colorCode: "#76c043",
    dataLoadDate: '2019-01-14',
    isDelete: 0,
    fileDocument: ''    
}, 
{
    win: 2345,
    cardId: 2,
    cardComponent: 'FULFILLMENT',
    cardSubComponent: 'MAXSS',
    cardTask: 'MAXSS=0',
    cardLevel: 'Item-Store', 
    taskCount: 98, 
    updateDate: '2019-01-14',
    colorCode: "#ffc220",
    dataLoadDate: '2019-01-14',
    isDelete: 0,
    fileDocument: ''    
}, 
{
    win: 2345,
    cardId: 3,
    cardComponent: 'DEMAND',
    cardSubComponent: 'Forecast Err',
    cardTask: 'Forecast Jump',
    cardLevel: 'Item', 
    taskCount: 18, 
    updateDate: '2019-01-14',
    colorCode: "#f47321",
    dataLoadDate: '2019-01-14',
    isDelete: 0,
    fileDocument: ''    
}, 
{
    win: 2345,
    cardId: 4,
    cardComponent: 'INVENTORY',
    cardSubComponent: 'DC Inv',
    cardTask: 'DC Trapped Inv',
    cardLevel: 'Item-DC', 
    taskCount: 2417, 
    updateDate: '2019-01-14',
    colorCode: "#76c043",
    dataLoadDate: '2019-01-14',
    isDelete: 0,
    fileDocument: ''    
}, 
{
    win: 2345,
    cardId: 5,
    cardComponent: 'INVENTORY',
    cardSubComponent: 'DC Inv',
    cardTask: 'DC Trapped Inv',
    cardLevel: 'Item-DC', 
    taskCount: 2417, 
    updateDate: '2019-01-14',
    colorCode: "#76c043",
    dataLoadDate: '2019-01-14',
    isDelete: 0,
    fileDocument: ''    
}, 
{
    win: 2345,
    cardId: 6,
    cardComponent: 'FULFILLMENT',
    cardSubComponent: 'MAXSS',
    cardTask: 'MAXSS=0',
    cardLevel: 'Item-Store', 
    taskCount: 98, 
    updateDate: '2019-01-14',
    colorCode: "#ffc220",
    dataLoadDate: '2019-01-14',
    isDelete: 0,
    fileDocument: ''    
}, 
{
    win: 2345,
    cardId: 7,
    cardComponent: 'DEMAND',
    cardSubComponent: 'Forecast Err',
    cardTask: 'Forecast Jump',
    cardLevel: 'Item', 
    taskCount: 18, 
    updateDate: '2019-01-14',
    colorCode: "#f47321",
    dataLoadDate: '2019-01-14',
    isDelete: 0,
    fileDocument: ''    
}, 
{
    win: 2345,
    cardId: 8,
    cardComponent: 'INVENTORY',
    cardSubComponent: 'DC Inv',
    cardTask: 'DC Trapped Inv',
    cardLevel: 'Item-DC', 
    taskCount: 2417, 
    updateDate: '2019-01-14',
    colorCode: "#76c043",
    dataLoadDate: '2019-01-14',
    isDelete: 0,
    fileDocument: ''    
}, 
{
    win: 2345,
    cardId: 9,
    cardComponent: 'INVENTORY',
    cardSubComponent: 'DC Inv',
    cardTask: 'DC Trapped Inv',
    cardLevel: 'Item-DC', 
    taskCount: 2417, 
    updateDate: '2019-01-14',
    colorCode: "#76c043",
    dataLoadDate: '2019-01-14',
    isDelete: 0,
    fileDocument: ''    
}, 
{
    win: 2345,
    cardId: 10,
    cardComponent: 'FULFILLMENT',
    cardSubComponent: 'MAXSS',
    cardTask: 'MAXSS=0',
    cardLevel: 'Item-Store', 
    taskCount: 98, 
    updateDate: '2019-01-14',
    colorCode: "#ffc220",
    dataLoadDate: '2019-01-14',
    isDelete: 0,
    fileDocument: ''    
}, 
{
    win: 2345,
    cardId: 11,
    cardComponent: 'DEMAND',
    cardSubComponent: 'Forecast Err',
    cardTask: 'Forecast Jump',
    cardLevel: 'Item', 
    taskCount: 18, 
    updateDate: '2019-01-14',
    colorCode: "#f47321",
    dataLoadDate: '2019-01-14',
    isDelete: 0,
    fileDocument: ''    
}, 
{
    win: 2345,
    cardId: 12,
    cardComponent: 'INVENTORY',
    cardSubComponent: 'DC Inv',
    cardTask: 'DC Trapped Inv',
    cardLevel: 'Item-DC', 
    taskCount: 2417, 
    updateDate: '2019-01-14',
    colorCode: "#76c043",
    dataLoadDate: '2019-01-14',
    isDelete: 0,
    fileDocument: ''    
}, 
{
    win: 2345,
    cardId: 13,
    cardComponent: 'INVENTORY',
    cardSubComponent: 'DC Inv',
    cardTask: 'DC Trapped Inv',
    cardLevel: 'Item-DC', 
    taskCount: 2417, 
    updateDate: '2019-01-14',
    colorCode: "#76c043",
    dataLoadDate: '2019-01-14',
    isDelete: 0,
    fileDocument: ''    
}, 
{
    win: 2345,
    cardId: 14,
    cardComponent: 'FULFILLMENT',
    cardSubComponent: 'MAXSS',
    cardTask: 'MAXSS=0',
    cardLevel: 'Item-Store', 
    taskCount: 98, 
    updateDate: '2019-01-14',
    colorCode: "#ffc220",
    dataLoadDate: '2019-01-14',
    isDelete: 0,
    fileDocument: ''    
}, 
{
    win: 2345,
    cardId: 15,
    cardComponent: 'DEMAND',
    cardSubComponent: 'Forecast Err',
    cardTask: 'Forecast Jump',
    cardLevel: 'Item', 
    taskCount: 18, 
    updateDate: '2019-01-14',
    colorCode: "#f47321",
    dataLoadDate: '2019-01-14',
    isDelete: 0,
    fileDocument: ''    
}, 
{
    win: 2345,
    cardId: 16,
    cardComponent: 'INVENTORY',
    cardSubComponent: 'DC Inv',
    cardTask: 'DC Trapped Inv',
    cardLevel: 'Item-DC', 
    taskCount: 2417, 
    updateDate: '2019-01-14',
    colorCode: "#76c043",
    dataLoadDate: '2019-01-14',
    isDelete: 0,
    fileDocument: ''    
}]